#! /bin/bash
#
# Starts the Autonomous Underwater Vehicle main program
# description: Starts the AUV
# processname: auv
# pidfile: /var/run/auvd.pid


service="auvd"
prog="/root/auv/DEBUG/auv"
pidfile="/var/run/${service}.pid"
lockfile="/var/lock/subsys/${service}"

# Sanity checks.
[ -x ${prog} ] || exit -1

start() {
	echo -n $"Starting ${service}: "
	if [ -e ${lockfile} ]; then
		if [ -e ${pidfile} ] && [ -e /proc/`cat ${pidfile}` ]; then
			echo
			failure
			echo -n $"cannot start ${service}: ${service} is already running.";
			echo
			return 1
		fi
	fi
	daemon --pidfile=${pidfile} ${prog}
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch ${lockfile};
	return $RETVAL
}

stop() {
	echo -n $"Stopping ${service}: "
	if [ ! -e ${lockfile} ]; then
		echo
		echo -n $"cannot stop ${service}: ${service} is not running."
		echo
		rm -f ${pidfile} ${lockfile};
		return 1;
	fi
	killproc -p ${pidfile}
	RETVAL=$?
	pkill -f auvd

	echo
	[ $RETVAL -eq 0 ] && rm -f ${pidfile} ${lockfile};
	return $RETVAL
}

rhstatus() {
	status ${service}
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		rhstatus
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart}"
		exit 1
esac
